# Generated by Django 6.0 on 2025-12-26 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aquarium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('volume_liters', models.PositiveIntegerField()),
                ('temperature', models.DecimalField(decimal_places=1, help_text='Temperature in °C', max_digits=4)),
                ('filtration_type', models.CharField(choices=[('internal', 'Internal filter'), ('external', 'External filter'), ('sponge', 'Sponge filter'), ('none', 'No filtration')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aquariums', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aquarium',
                'verbose_name_plural': 'Aquariums',
                'ordering': ['-created_at'],
            },
        ),
    ]
