# Generated by Django 6.0 on 2026-01-11 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquariums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AquariumPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nitrate_absorption', models.DecimalField(decimal_places=3, help_text='NO3 ppm absorbed per day', max_digits=6)),
                ('phosphate_absorption', models.DecimalField(decimal_places=3, help_text='PO4 ppm absorbed per day', max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aquarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='aquariums.aquarium')),
            ],
        ),
    ]
