# Generated by Django 6.0 on 2026-01-15 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquariums', '0002_aquariumplant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aquarium',
            options={'ordering': ['-created_at'], 'verbose_name': 'Аквариум', 'verbose_name_plural': 'Аквариумы'},
        ),
        migrations.AlterModelOptions(
            name='aquariumplant',
            options={'verbose_name': 'Растение', 'verbose_name_plural': 'Растения'},
        ),
        migrations.AlterField(
            model_name='aquarium',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='aquarium',
            name='filtration_type',
            field=models.CharField(choices=[('internal', 'Внутренний фильтр'), ('external', 'Внешний фильтр'), ('sponge', 'Губчатый фильтр'), ('none', 'Без фильтрации')], max_length=20, verbose_name='Тип фильтрации'),
        ),
        migrations.AlterField(
            model_name='aquarium',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='aquarium',
            name='temperature',
            field=models.DecimalField(decimal_places=1, help_text='Температура воды в °C', max_digits=4, verbose_name='Температура (°C)'),
        ),
        migrations.AlterField(
            model_name='aquarium',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aquariums', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='aquarium',
            name='volume_liters',
            field=models.PositiveIntegerField(verbose_name='Объём (л)'),
        ),
        migrations.AlterField(
            model_name='aquariumplant',
            name='aquarium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='aquariums.aquarium', verbose_name='Аквариум'),
        ),
        migrations.AlterField(
            model_name='aquariumplant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='aquariumplant',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название растения'),
        ),
        migrations.AlterField(
            model_name='aquariumplant',
            name='nitrate_absorption',
            field=models.DecimalField(decimal_places=3, help_text='Сколько нитратов (NO₃) растение поглощает в сутки (ppm/день)', max_digits=6, verbose_name='Поглощение NO₃ (ppm/день)'),
        ),
        migrations.AlterField(
            model_name='aquariumplant',
            name='phosphate_absorption',
            field=models.DecimalField(decimal_places=3, help_text='Сколько фосфатов (PO₄) растение поглощает в сутки (ppm/день)', max_digits=6, verbose_name='Поглощение PO₄ (ppm/день)'),
        ),
    ]
