# Generated by Django 6.0 on 2026-01-16 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquariums', '0003_alter_aquarium_options_alter_aquariumplant_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название растения')),
                ('nitrate_absorption', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Поглощение NO₃ (ppm/день)')),
                ('phosphate_absorption', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Поглощение PO₄ (ppm/день)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Аквариумное растение',
                'verbose_name_plural': 'Аквариумные растения',
            },
        ),
        migrations.AlterModelOptions(
            name='aquariumplant',
            options={},
        ),
        migrations.RemoveField(
            model_name='aquariumplant',
            name='name',
        ),
        migrations.RemoveField(
            model_name='aquariumplant',
            name='nitrate_absorption',
        ),
        migrations.RemoveField(
            model_name='aquariumplant',
            name='phosphate_absorption',
        ),
        migrations.AddField(
            model_name='aquariumplant',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='aquariumplant',
            name='aquarium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='aquariums.aquarium'),
        ),
        migrations.AlterField(
            model_name='aquariumplant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='aquariumplant',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aquariums', to='aquariums.plant'),
        ),
    ]
