# Generated by Django 6.0 on 2026-01-16 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquariums', '0004_plant_alter_aquariumplant_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aquariumplant',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aquariums', to='aquariums.plant'),
        ),
    ]
