# Generated by Django 6.0 on 2025-12-27 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aquariums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('average_weight_grams', models.DecimalField(decimal_places=2, max_digits=6)),
                ('feeding_coefficient', models.DecimalField(decimal_places=3, max_digits=6)),
                ('waste_factor', models.DecimalField(decimal_places=3, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fish species',
                'verbose_name_plural': 'Fish species',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AquariumFish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aquarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fish', to='aquariums.aquarium')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aquarium_entries', to='fish.fishspecies')),
            ],
            options={
                'verbose_name': 'Aquarium fish',
                'verbose_name_plural': 'Aquarium fish',
                'constraints': [models.UniqueConstraint(fields=('aquarium', 'species'), name='uniq_species_per_aquarium')],
            },
        ),
    ]
