# Generated by Django 6.0 on 2026-01-15 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquariums', '0003_alter_aquarium_options_alter_aquariumplant_options_and_more'),
        ('fish', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aquariumfish',
            options={'verbose_name': 'Рыбы в аквариуме', 'verbose_name_plural': 'Рыбы в аквариумах'},
        ),
        migrations.AlterModelOptions(
            name='fishspecies',
            options={'ordering': ['name'], 'verbose_name': 'Вид рыбы', 'verbose_name_plural': 'Виды рыб'},
        ),
        migrations.AlterField(
            model_name='aquariumfish',
            name='aquarium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fish', to='aquariums.aquarium', verbose_name='Аквариум'),
        ),
        migrations.AlterField(
            model_name='aquariumfish',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='aquariumfish',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='aquariumfish',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aquarium_entries', to='fish.fishspecies', verbose_name='Вид рыбы'),
        ),
        migrations.AlterField(
            model_name='fishspecies',
            name='average_weight_grams',
            field=models.DecimalField(decimal_places=2, help_text='Средний вес одной особи в граммах', max_digits=6, verbose_name='Средний вес (г)'),
        ),
        migrations.AlterField(
            model_name='fishspecies',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='fishspecies',
            name='feeding_coefficient',
            field=models.DecimalField(decimal_places=3, help_text='Коэффициент для расчёта суточной нормы корма', max_digits=6, verbose_name='Коэффициент кормления'),
        ),
        migrations.AlterField(
            model_name='fishspecies',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='fishspecies',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Вид рыбы'),
        ),
        migrations.AlterField(
            model_name='fishspecies',
            name='waste_factor',
            field=models.DecimalField(decimal_places=3, help_text='Относительный вклад вида в органическую нагрузку', max_digits=6, verbose_name='Коэффициент загрязнения'),
        ),
    ]
