# Generated by Django 6.0 on 2025-12-27 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feeding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterQualityForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitrate_ppm', models.DecimalField(decimal_places=3, max_digits=10)),
                ('phosphate_ppm', models.DecimalField(decimal_places=3, max_digits=10)),
                ('organic_load_index', models.DecimalField(decimal_places=3, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feeding_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='water_forecast', to='feeding.feedingplan')),
            ],
            options={
                'verbose_name': 'Water quality forecast',
                'verbose_name_plural': 'Water quality forecasts',
                'ordering': ['-created_at'],
            },
        ),
    ]
