# Generated by Django 6.0 on 2026-01-11 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquariums', '0001_initial'),
        ('water_quality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_interval', models.PositiveSmallIntegerField(help_text='Every N days')),
                ('percent', models.DecimalField(decimal_places=2, help_text='Percent of water changed', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aquarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_changes', to='aquariums.aquarium')),
            ],
            options={
                'verbose_name': 'Water change',
                'verbose_name_plural': 'Water changes',
            },
        ),
    ]
