# Generated by Django 6.0 on 2026-01-15 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquariums', '0003_alter_aquarium_options_alter_aquariumplant_options_and_more'),
        ('water_quality', '0002_waterchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterchange',
            name='aquarium',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='water_change', to='aquariums.aquarium'),
        ),
    ]
