# Generated by Django 6.0 on 2026-01-15 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquariums', '0003_alter_aquarium_options_alter_aquariumplant_options_and_more'),
        ('feeding', '0002_alter_feedingplan_options_alter_feedingplan_aquarium_and_more'),
        ('water_quality', '0003_alter_waterchange_aquarium'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waterchange',
            options={'verbose_name': 'Подмена воды', 'verbose_name_plural': 'Подмены воды'},
        ),
        migrations.AlterModelOptions(
            name='waterqualityforecast',
            options={'ordering': ['-created_at'], 'verbose_name': 'Прогноз качества воды', 'verbose_name_plural': 'Прогнозы качества воды'},
        ),
        migrations.AlterField(
            model_name='waterchange',
            name='aquarium',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='water_change', to='aquariums.aquarium', verbose_name='Аквариум'),
        ),
        migrations.AlterField(
            model_name='waterchange',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='waterchange',
            name='day_interval',
            field=models.PositiveSmallIntegerField(help_text='Каждые N дней', verbose_name='Интервал (дней)'),
        ),
        migrations.AlterField(
            model_name='waterchange',
            name='percent',
            field=models.DecimalField(decimal_places=2, help_text='Процент объёма воды, который меняется за одну подмену', max_digits=5, verbose_name='Процент подмены (%)'),
        ),
        migrations.AlterField(
            model_name='waterqualityforecast',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='waterqualityforecast',
            name='feeding_plan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='water_forecast', to='feeding.feedingplan', verbose_name='План кормления'),
        ),
        migrations.AlterField(
            model_name='waterqualityforecast',
            name='nitrate_ppm',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Нитраты NO₃ (ppm)'),
        ),
        migrations.AlterField(
            model_name='waterqualityforecast',
            name='organic_load_index',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Индекс органической нагрузки'),
        ),
        migrations.AlterField(
            model_name='waterqualityforecast',
            name='phosphate_ppm',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Фосфаты PO₄ (ppm)'),
        ),
    ]
