# Generated by Django 6.0 on 2025-12-27 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aquariums', '0001_initial'),
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_amount_grams', models.DecimalField(decimal_places=3, max_digits=10)),
                ('feedings_per_day', models.PositiveSmallIntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aquarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_plans', to='aquariums.aquarium')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feeding_plans', to='food.food')),
            ],
            options={
                'verbose_name': 'Feeding plan',
                'verbose_name_plural': 'Feeding plans',
                'ordering': ['-created_at'],
            },
        ),
    ]
