# Generated by Django 6.0 on 2026-01-15 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquariums', '0003_alter_aquarium_options_alter_aquariumplant_options_and_more'),
        ('feeding', '0001_initial'),
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedingplan',
            options={'ordering': ['-created_at'], 'verbose_name': 'План кормления', 'verbose_name_plural': 'Планы кормления'},
        ),
        migrations.AlterField(
            model_name='feedingplan',
            name='aquarium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_plans', to='aquariums.aquarium', verbose_name='Аквариум'),
        ),
        migrations.AlterField(
            model_name='feedingplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='feedingplan',
            name='daily_amount_grams',
            field=models.DecimalField(decimal_places=3, help_text='Общее количество корма в граммах на сутки', max_digits=10, verbose_name='Суточная норма (г)'),
        ),
        migrations.AlterField(
            model_name='feedingplan',
            name='feedings_per_day',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Кормлений в день'),
        ),
        migrations.AlterField(
            model_name='feedingplan',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feeding_plans', to='food.food', verbose_name='Корм'),
        ),
    ]
