# Generated by Django 6.0 on 2025-12-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('protein_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fat_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fiber_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ash_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pollution_index', models.DecimalField(decimal_places=3, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Food',
                'verbose_name_plural': 'Food',
                'ordering': ['name'],
            },
        ),
    ]
