# Generated by Django 6.0 on 2026-01-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['name'], 'verbose_name': 'Корм', 'verbose_name_plural': 'Корма'},
        ),
        migrations.AlterField(
            model_name='food',
            name='ash_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Зола (%)'),
        ),
        migrations.AlterField(
            model_name='food',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Жиры (%)'),
        ),
        migrations.AlterField(
            model_name='food',
            name='fiber_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Клетчатка (%)'),
        ),
        migrations.AlterField(
            model_name='food',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='food',
            name='pollution_index',
            field=models.DecimalField(decimal_places=3, help_text='Условный показатель, отражающий влияние корма на органическую нагрузку', max_digits=6, verbose_name='Индекс загрязнения'),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Белок (%)'),
        ),
    ]
